//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaphiqSaleApp.BaphiqSale {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.baphiq.jo.hyweb/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.baphiq.jo.hyweb/", ConfigurationName="BaphiqSale.BaphiqSale")]
    public interface BaphiqSale {
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/qryPesticideUseRangeRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/qryPesticideUseRangeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BaphiqSaleApp.BaphiqSale.Exception), Action="http://ws.baphiq.jo.hyweb/BaphiqSale/qryPesticideUseRange/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse qryPesticideUseRange(BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/qryPesticideUseRangeRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/qryPesticideUseRangeResponse")]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse> qryPesticideUseRangeAsync(BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/salesDataDownloadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/salesDataDownloadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse salesDataDownload(BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/salesDataDownloadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/salesDataDownloadResponse")]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse> salesDataDownloadAsync(BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/DisposalRecordRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/DisposalRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BaphiqSaleApp.BaphiqSale.Exception), Action="http://ws.baphiq.jo.hyweb/BaphiqSale/DisposalRecord/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BaphiqSaleApp.BaphiqSale.DisposalRecordResponse DisposalRecord(BaphiqSaleApp.BaphiqSale.DisposalRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/DisposalRecordRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/DisposalRecordResponse")]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.DisposalRecordResponse> DisposalRecordAsync(BaphiqSaleApp.BaphiqSale.DisposalRecordRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellPersonUploadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/SellPersonUploadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BaphiqSaleApp.BaphiqSale.Exception), Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellPersonUpload/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse SellPersonUpload(BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellPersonUploadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/SellPersonUploadResponse")]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse> SellPersonUploadAsync(BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest request);
        
        // CODEGEN: 參數 'return' 需要無法以參數模式來擷取的其他架構資訊。特定屬性為 'System.Xml.Serialization.XmlElementAttribute'。
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellStoreUploadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/SellStoreUploadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BaphiqSaleApp.BaphiqSale.Exception), Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellStoreUpload/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse SellStoreUpload(BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.baphiq.jo.hyweb/BaphiqSale/SellStoreUploadRequest", ReplyAction="http://ws.baphiq.jo.hyweb/BaphiqSale/SellStoreUploadResponse")]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse> SellStoreUploadAsync(BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="qryPesticideUseRange", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class qryPesticideUseRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trustId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string barcode;
        
        public qryPesticideUseRangeRequest() {
        }
        
        public qryPesticideUseRangeRequest(string trustId, string barcode) {
            this.trustId = trustId;
            this.barcode = barcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="qryPesticideUseRangeResponse", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class qryPesticideUseRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public qryPesticideUseRangeResponse() {
        }
        
        public qryPesticideUseRangeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="salesDataDownload", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class salesDataDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trustId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestStartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string requestEndDate;
        
        public salesDataDownloadRequest() {
        }
        
        public salesDataDownloadRequest(string trustId, string requestStartDate, string requestEndDate) {
            this.trustId = trustId;
            this.requestStartDate = requestStartDate;
            this.requestEndDate = requestEndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="salesDataDownloadResponse", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class salesDataDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public salesDataDownloadResponse() {
        }
        
        public salesDataDownloadResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisposalRecord", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class DisposalRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loginId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inputXML;
        
        public DisposalRecordRequest() {
        }
        
        public DisposalRecordRequest(string loginId, string inputXML) {
            this.loginId = loginId;
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisposalRecordResponse", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class DisposalRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public DisposalRecordResponse() {
        }
        
        public DisposalRecordResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellPersonUpload", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class SellPersonUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loginId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inputXML;
        
        public SellPersonUploadRequest() {
        }
        
        public SellPersonUploadRequest(string loginId, string inputXML) {
            this.loginId = loginId;
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellPersonUploadResponse", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class SellPersonUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public SellPersonUploadResponse() {
        }
        
        public SellPersonUploadResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellStoreUpload", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class SellStoreUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loginId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inputXML;
        
        public SellStoreUploadRequest() {
        }
        
        public SellStoreUploadRequest(string loginId, string inputXML) {
            this.loginId = loginId;
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SellStoreUploadResponse", WrapperNamespace="http://ws.baphiq.jo.hyweb/", IsWrapped=true)]
    public partial class SellStoreUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.baphiq.jo.hyweb/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public SellStoreUploadResponse() {
        }
        
        public SellStoreUploadResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaphiqSaleChannel : BaphiqSaleApp.BaphiqSale.BaphiqSale, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaphiqSaleClient : System.ServiceModel.ClientBase<BaphiqSaleApp.BaphiqSale.BaphiqSale>, BaphiqSaleApp.BaphiqSale.BaphiqSale {
        
        public BaphiqSaleClient() {
        }
        
        public BaphiqSaleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaphiqSaleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaphiqSaleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaphiqSaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse BaphiqSaleApp.BaphiqSale.BaphiqSale.qryPesticideUseRange(BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest request) {
            return base.Channel.qryPesticideUseRange(request);
        }
        
        public string qryPesticideUseRange(string trustId, string barcode) {
            BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest inValue = new BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest();
            inValue.trustId = trustId;
            inValue.barcode = barcode;
            BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse retVal = ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).qryPesticideUseRange(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse> BaphiqSaleApp.BaphiqSale.BaphiqSale.qryPesticideUseRangeAsync(BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest request) {
            return base.Channel.qryPesticideUseRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeResponse> qryPesticideUseRangeAsync(string trustId, string barcode) {
            BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest inValue = new BaphiqSaleApp.BaphiqSale.qryPesticideUseRangeRequest();
            inValue.trustId = trustId;
            inValue.barcode = barcode;
            return ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).qryPesticideUseRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse BaphiqSaleApp.BaphiqSale.BaphiqSale.salesDataDownload(BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest request) {
            return base.Channel.salesDataDownload(request);
        }
        
        public string salesDataDownload(string trustId, string requestStartDate, string requestEndDate) {
            BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest inValue = new BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest();
            inValue.trustId = trustId;
            inValue.requestStartDate = requestStartDate;
            inValue.requestEndDate = requestEndDate;
            BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse retVal = ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).salesDataDownload(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse> BaphiqSaleApp.BaphiqSale.BaphiqSale.salesDataDownloadAsync(BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest request) {
            return base.Channel.salesDataDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.salesDataDownloadResponse> salesDataDownloadAsync(string trustId, string requestStartDate, string requestEndDate) {
            BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest inValue = new BaphiqSaleApp.BaphiqSale.salesDataDownloadRequest();
            inValue.trustId = trustId;
            inValue.requestStartDate = requestStartDate;
            inValue.requestEndDate = requestEndDate;
            return ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).salesDataDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaphiqSaleApp.BaphiqSale.DisposalRecordResponse BaphiqSaleApp.BaphiqSale.BaphiqSale.DisposalRecord(BaphiqSaleApp.BaphiqSale.DisposalRecordRequest request) {
            return base.Channel.DisposalRecord(request);
        }
        
        public string DisposalRecord(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.DisposalRecordRequest inValue = new BaphiqSaleApp.BaphiqSale.DisposalRecordRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            BaphiqSaleApp.BaphiqSale.DisposalRecordResponse retVal = ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).DisposalRecord(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.DisposalRecordResponse> BaphiqSaleApp.BaphiqSale.BaphiqSale.DisposalRecordAsync(BaphiqSaleApp.BaphiqSale.DisposalRecordRequest request) {
            return base.Channel.DisposalRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.DisposalRecordResponse> DisposalRecordAsync(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.DisposalRecordRequest inValue = new BaphiqSaleApp.BaphiqSale.DisposalRecordRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            return ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).DisposalRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse BaphiqSaleApp.BaphiqSale.BaphiqSale.SellPersonUpload(BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest request) {
            return base.Channel.SellPersonUpload(request);
        }
        
        public string SellPersonUpload(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest inValue = new BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse retVal = ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).SellPersonUpload(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse> BaphiqSaleApp.BaphiqSale.BaphiqSale.SellPersonUploadAsync(BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest request) {
            return base.Channel.SellPersonUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellPersonUploadResponse> SellPersonUploadAsync(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest inValue = new BaphiqSaleApp.BaphiqSale.SellPersonUploadRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            return ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).SellPersonUploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse BaphiqSaleApp.BaphiqSale.BaphiqSale.SellStoreUpload(BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest request) {
            return base.Channel.SellStoreUpload(request);
        }
        
        public string SellStoreUpload(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest inValue = new BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse retVal = ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).SellStoreUpload(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse> BaphiqSaleApp.BaphiqSale.BaphiqSale.SellStoreUploadAsync(BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest request) {
            return base.Channel.SellStoreUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<BaphiqSaleApp.BaphiqSale.SellStoreUploadResponse> SellStoreUploadAsync(string loginId, string inputXML) {
            BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest inValue = new BaphiqSaleApp.BaphiqSale.SellStoreUploadRequest();
            inValue.loginId = loginId;
            inValue.inputXML = inputXML;
            return ((BaphiqSaleApp.BaphiqSale.BaphiqSale)(this)).SellStoreUploadAsync(inValue);
        }
    }
}
